name: hikvision_Package
on: [push, pull_request]

jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller
          
      - name: Package 
        run: |
          pyinstaller main.py
          
      - uses: actions/upload-artifact@v3
        with:
          name: Windows artifact
          path: dist/main.exe
          
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller pyqt5==5.15.6
      - name: Build hikvision
        run: |
          pyrcc5 -o libs/resources.py resources.qrc
      - name: Package hikvision
        run: |
          pyinstaller -c main.py
      - uses: actions/upload-artifact@v3
        with:
          name: Linux artifact
          path: dist/main
