name: Release hikvision
on: [push, pull_request]
jobs:
  release:
    name: Create Release
    runs-on: windows-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build:
    name: Build hikvision
    needs: release
    runs-on:  windows-latest
    defaults:
      run:
        working-directory: hikvision

    steps:
      - name: Setup Python Environment
        run: |
            pip3 install pyinstaller
    
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Test Release
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event. ${{ needs.release.outputs.upload_url }}"  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller        

      - name: Build
        run: |
          pyinstaller -F main.py -n hikvision        

      - name: Package
        working-directory: .
        run: |
          tar -zcvf hikvision.tar.gz -C hikvision/dist *        

      - name: Upload assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: hikvision.tar.gz
          asset_name: hikvision.tar.gz
          asset_content_type: application/gzip
