name: hikvision_Package
on: [push, pull_request]

jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller
          
      - name: Package 
        run: |
          pyinstaller main.py

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/main/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
          
      - uses: actions/upload-artifact@v3
        with:
          name: Windows artifact
          path: dist/main/main.exe

      - name: Upload To WeTransfer
        run: |
          ./transfer wet -s -p 16 --no-progress dist/main/main.exe 2>&1 | tee wetransfer.log 
          echo "::warning file=Firmware-Wetransfer.com::$(cat wetransfer.log | grep https)"    
          
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller
      - name: Package hikvision
        run: |
          pyinstaller -c main.py
      - uses: actions/upload-artifact@v3
        with:
          name: Linux artifact
          path: dist/main
